# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaLogin(object):
    def setupUi(self, ventanaLogin):
        ventanaLogin.setObjectName("ventanaLogin")
        ventanaLogin.resize(640, 480)
        ventanaLogin.setMinimumSize(QtCore.QSize(640, 480))
        ventanaLogin.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/error_404-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ventanaLogin.setWindowIcon(icon)
        ventanaLogin.setStyleSheet("QWidget{\n"
"    background-color: rgb(52, 2, 2);\n"
"\n"
"}\n"
"\n"
"QFrame#frame_bot{    \n"
"    background-image: url(:/images/images/fondoRojo.jpeg);\n"
"}\n"
"\n"
"QFrame{\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame#frame_top{\n"
"    background-image: url(:/images/images/fondoRojo.jpeg);\n"
"}\n"
"QLabel{\n"
"    background: transparent;\n"
"    color: white;\n"
"    font-size: 20px;\n"
"    font: Ubuntu bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"color: black;\n"
"background: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"color: white;\n"
"background: qlineargradient(spread:pad, x1:0.800995, y1:0.256182, x2:1, y2:0, stop:0 rgba(164, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"\n"
"QLabel#label_titulo{\n"
"    color: white;\n"
"    background: transparent;\n"
"    font-size: 33px;\n"
"    font-family: Arial Black;\n"
"}\n"
"\n"
"")
        self.label_usuario = QtWidgets.QLabel(ventanaLogin)
        self.label_usuario.setGeometry(QtCore.QRect(180, 150, 331, 28))
        self.label_usuario.setObjectName("label_usuario")
        self.frame_top = QtWidgets.QFrame(ventanaLogin)
        self.frame_top.setGeometry(QtCore.QRect(10, 10, 621, 91))
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.label_titulo = QtWidgets.QLabel(self.frame_top)
        self.label_titulo.setGeometry(QtCore.QRect(10, -20, 611, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.lineEdit_user = QtWidgets.QLineEdit(ventanaLogin)
        self.lineEdit_user.setGeometry(QtCore.QRect(180, 180, 271, 26))
        self.lineEdit_user.setText("")
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_password = QtWidgets.QLineEdit(ventanaLogin)
        self.lineEdit_password.setGeometry(QtCore.QRect(180, 250, 271, 26))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_password = QtWidgets.QLabel(ventanaLogin)
        self.label_password.setGeometry(QtCore.QRect(180, 225, 131, 17))
        self.label_password.setObjectName("label_password")
        self.pushButton_login = QtWidgets.QPushButton(ventanaLogin)
        self.pushButton_login.setGeometry(QtCore.QRect(9, 331, 202, 25))
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_register = QtWidgets.QPushButton(ventanaLogin)
        self.pushButton_register.setGeometry(QtCore.QRect(217, 331, 203, 25))
        self.pushButton_register.setObjectName("pushButton_register")
        self.pushButton_salir = QtWidgets.QPushButton(ventanaLogin)
        self.pushButton_salir.setGeometry(QtCore.QRect(426, 331, 202, 25))
        self.pushButton_salir.setObjectName("pushButton_salir")
        self.frame_bot = QtWidgets.QFrame(ventanaLogin)
        self.frame_bot.setGeometry(QtCore.QRect(10, 110, 621, 361))
        self.frame_bot.setStyleSheet("")
        self.frame_bot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bot.setObjectName("frame_bot")
        self.label_gobierno = QtWidgets.QLabel(self.frame_bot)
        self.label_gobierno.setGeometry(QtCore.QRect(0, 270, 641, 81))
        self.label_gobierno.setText("")
        self.label_gobierno.setPixmap(QtGui.QPixmap(":/images/images/parte_inferior1.jpg"))
        self.label_gobierno.setScaledContents(True)
        self.label_gobierno.setObjectName("label_gobierno")
        self.label_error404 = QtWidgets.QLabel(ventanaLogin)
        self.label_error404.setGeometry(QtCore.QRect(300, 70, 61, 61))
        self.label_error404.setText("")
        self.label_error404.setPixmap(QtGui.QPixmap(":/images/images/585e4beacb11b227491c3399.png"))
        self.label_error404.setScaledContents(True)
        self.label_error404.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error404.setWordWrap(False)
        self.label_error404.setObjectName("label_error404")
        self.frame_bot.raise_()
        self.frame_top.raise_()
        self.label_usuario.raise_()
        self.lineEdit_user.raise_()
        self.lineEdit_password.raise_()
        self.label_password.raise_()
        self.label_error404.raise_()
        self.pushButton_login.raise_()
        self.pushButton_salir.raise_()
        self.pushButton_register.raise_()

        self.retranslateUi(ventanaLogin)
        QtCore.QMetaObject.connectSlotsByName(ventanaLogin)

    def retranslateUi(self, ventanaLogin):
        _translate = QtCore.QCoreApplication.translate
        ventanaLogin.setWindowTitle(_translate("ventanaLogin", "Iniciar sesión o registrarse"))
        self.label_usuario.setText(_translate("ventanaLogin", "Usuario"))
        self.label_titulo.setText(_translate("ventanaLogin", "Sistema de Gestión Contable"))
        self.label_password.setText(_translate("ventanaLogin", "Contraseña"))
        self.pushButton_login.setText(_translate("ventanaLogin", "Ingresar"))
        self.pushButton_register.setText(_translate("ventanaLogin", "Crear cuenta"))
        self.pushButton_salir.setText(_translate("ventanaLogin", "Salir"))
import source_rc
