# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_realizar_consulta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_realizar_consulta(object):
    def setupUi(self, ventana_realizar_consulta):
        ventana_realizar_consulta.setObjectName("ventana_realizar_consulta")
        ventana_realizar_consulta.resize(640, 480)
        ventana_realizar_consulta.setMinimumSize(QtCore.QSize(640, 480))
        ventana_realizar_consulta.setMaximumSize(QtCore.QSize(640, 480))
        ventana_realizar_consulta.setStyleSheet("QWidget#ventana_realizar_consulta{\n"
"    background-color: rgb(52, 2, 2);\n"
"}\n"
"\n"
"QFrame#frame_top{    \n"
"    background-image: url(:/images/images/fondoRojo.jpeg);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QLabel#label_titulo{\n"
"    color: white;\n"
"    background: transparent;\n"
"    font-size: 33px;\n"
"    font-family: Arial Black;\n"
"}\n"
"\n"
"QLabel#label_error404{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QFrame#frame_bottom{\n"
"    width: 260px;\n"
"    height: 260px;\n"
"    border-radius: 15px;    \n"
"    background-image: url(:/images/images/fondoRojo.jpeg);\n"
"}\n"
"\n"
"QListWidget{    \n"
"    background-color: black;\n"
"    border-radius: 15px;\n"
"    color: rgb(99, 245, 77);\n"
"}\n"
"\n"
"QLabel#label_descripcion{\n"
"    background: transparent;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-family: Sans;\n"
"}")
        self.frame_top = QtWidgets.QFrame(ventana_realizar_consulta)
        self.frame_top.setGeometry(QtCore.QRect(10, 10, 621, 91))
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.label_titulo = QtWidgets.QLabel(self.frame_top)
        self.label_titulo.setGeometry(QtCore.QRect(10, -20, 611, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.frame_bottom = QtWidgets.QFrame(ventana_realizar_consulta)
        self.frame_bottom.setGeometry(QtCore.QRect(10, 110, 621, 361))
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.listWidget = QtWidgets.QListWidget(self.frame_bottom)
        self.listWidget.setGeometry(QtCore.QRect(0, 40, 621, 221))
        self.listWidget.setObjectName("listWidget")
        self.label_descripcion = QtWidgets.QLabel(self.frame_bottom)
        self.label_descripcion.setGeometry(QtCore.QRect(10, -10, 611, 71))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_descripcion.setFont(font)
        self.label_descripcion.setTextFormat(QtCore.Qt.PlainText)
        self.label_descripcion.setObjectName("label_descripcion")
        self.label_gobierno = QtWidgets.QLabel(self.frame_bottom)
        self.label_gobierno.setGeometry(QtCore.QRect(0, 260, 641, 81))
        self.label_gobierno.setText("")
        self.label_gobierno.setPixmap(QtGui.QPixmap(":/images/images/parte inferior1.jpg"))
        self.label_gobierno.setScaledContents(True)
        self.label_gobierno.setObjectName("label_gobierno")
        self.label_descripcion.raise_()
        self.listWidget.raise_()
        self.label_gobierno.raise_()
        self.label_error404 = QtWidgets.QLabel(ventana_realizar_consulta)
        self.label_error404.setGeometry(QtCore.QRect(270, 60, 81, 61))
        self.label_error404.setText("")
        self.label_error404.setPixmap(QtGui.QPixmap(":/images/images/iconobuscar.png"))
        self.label_error404.setScaledContents(True)
        self.label_error404.setObjectName("label_error404")
        self.frame_bottom.raise_()
        self.frame_top.raise_()
        self.label_error404.raise_()

        self.retranslateUi(ventana_realizar_consulta)
        QtCore.QMetaObject.connectSlotsByName(ventana_realizar_consulta)

    def retranslateUi(self, ventana_realizar_consulta):
        _translate = QtCore.QCoreApplication.translate
        ventana_realizar_consulta.setWindowTitle(_translate("ventana_realizar_consulta", "Realizar consultas"))
        self.label_titulo.setText(_translate("ventana_realizar_consulta", "Sistema de Gestión Contable"))
        self.label_descripcion.setText(_translate("ventana_realizar_consulta", "Aquí se muestran todos los movimientos registrados en el sistema"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_realizar_consulta = QtWidgets.QWidget()
    ui = Ui_ventana_realizar_consulta()
    ui.setupUi(ventana_realizar_consulta)
    ventana_realizar_consulta.show()
    sys.exit(app.exec_())
