# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_SGC.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_SGC(object):
    def setupUi(self, ventana_SGC):
        ventana_SGC.setObjectName("ventana_SGC")
        ventana_SGC.resize(640, 480)
        ventana_SGC.setMinimumSize(QtCore.QSize(640, 480))
        ventana_SGC.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/error_404-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ventana_SGC.setWindowIcon(icon)
        ventana_SGC.setStyleSheet("QWidget#ventana_SGC{\n"
"    background-color: rgb(52, 2, 2);\n"
"}\n"
"\n"
"QFrame#frame_top{\n"
"    background-image: url(:/images/images/fondoRojo.jpeg);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame#frame_bottom{\n"
"    width: 260px;\n"
"    height: 260px;\n"
"    border-radius: 15px;\n"
"    background-image: url(:/images/images/fondoRojo.jpeg);\n"
"}\n"
"\n"
"QLabel#label_404{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#label_titulo{\n"
"    color: white;\n"
"    background: transparent;\n"
"    font-size: 33px;\n"
"    font-family: Arial Black;\n"
"}\n"
"\n"
"QPushButton#pushButton_salir{\n"
"color: white;\n"
"background: qlineargradient(spread:pad, x1:0.800995, y1:0.256182, x2:1, y2:0, stop:0 rgba(164, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton#pushButton_registrarMovimientos{\n"
"background: qlineargradient(spread:pad, x1:0.800995, y1:0.256182, x2:1, y2:0, stop:0 rgba(164, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color: white;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QPushButton#pushButton_realizarConsultas{\n"
"background: qlineargradient(spread:pad, x1:0.800995, y1:0.256182, x2:1, y2:0, stop:0 rgba(164, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color: white;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLabel#label_realizarConsultas{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#label_registrarMovimientos{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel{\n"
"    background: transparent;\n"
"    color: black;\n"
"    font-size: 20px;\n"
"    font: Ubuntu bold;\n"
"}\n"
"\n"
"")
        self.frame_top = QtWidgets.QFrame(ventana_SGC)
        self.frame_top.setGeometry(QtCore.QRect(10, 10, 621, 91))
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.label_titulo = QtWidgets.QLabel(self.frame_top)
        self.label_titulo.setGeometry(QtCore.QRect(0, -10, 621, 61))
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.frame_bottom = QtWidgets.QFrame(ventana_SGC)
        self.frame_bottom.setGeometry(QtCore.QRect(10, 110, 621, 361))
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.pushButton_salir = QtWidgets.QPushButton(self.frame_bottom)
        self.pushButton_salir.setGeometry(QtCore.QRect(520, 230, 89, 25))
        self.pushButton_salir.setObjectName("pushButton_salir")
        self.pushButton_registrarMovimientos = QtWidgets.QPushButton(self.frame_bottom)
        self.pushButton_registrarMovimientos.setGeometry(QtCore.QRect(0, 93, 300, 81))
        self.pushButton_registrarMovimientos.setObjectName("pushButton_registrarMovimientos")
        self.pushButton_realizarConsultas = QtWidgets.QPushButton(self.frame_bottom)
        self.pushButton_realizarConsultas.setGeometry(QtCore.QRect(320, 93, 300, 81))
        self.pushButton_realizarConsultas.setObjectName("pushButton_realizarConsultas")
        self.label_gobierno = QtWidgets.QLabel(self.frame_bottom)
        self.label_gobierno.setGeometry(QtCore.QRect(0, 270, 641, 81))
        self.label_gobierno.setText("")
        self.label_gobierno.setPixmap(QtGui.QPixmap(":/images/images/parte_inferior1.jpg"))
        self.label_gobierno.setScaledContents(True)
        self.label_gobierno.setObjectName("label_gobierno")
        self.label_404 = QtWidgets.QLabel(ventana_SGC)
        self.label_404.setGeometry(QtCore.QRect(270, 60, 121, 101))
        self.label_404.setText("")
        self.label_404.setPixmap(QtGui.QPixmap(":/images/images/searchIcon.png"))
        self.label_404.setScaledContents(True)
        self.label_404.setObjectName("label_404")

        self.retranslateUi(ventana_SGC)
        QtCore.QMetaObject.connectSlotsByName(ventana_SGC)

    def retranslateUi(self, ventana_SGC):
        _translate = QtCore.QCoreApplication.translate
        ventana_SGC.setWindowTitle(_translate("ventana_SGC", "Sistema de Gestión Contable"))
        self.label_titulo.setText(_translate("ventana_SGC", "Sistema de Gestión Contable"))
        self.pushButton_salir.setText(_translate("ventana_SGC", "Salir"))
        self.pushButton_registrarMovimientos.setText(_translate("ventana_SGC", "Registrar \n"
"movimientos"))
        self.pushButton_realizarConsultas.setText(_translate("ventana_SGC", "Realizar \n"
"consultas"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_SGC = QtWidgets.QWidget()
    ui = Ui_ventana_SGC()
    ui.setupUi(ventana_SGC)
    ventana_SGC.show()
    sys.exit(app.exec_())
